using System.Collections.Generic;

namespace officialApp.Models;

public static class UKConstituencies
{
    public static readonly List<string> Constituencies = new()
    {
        "Aberavon",
        "Aberconwy",
        "Aberdeen North",
        "Aberdeen South",
        "Airdrie and Shotts",
        "Aldershot",
        "Alyn and Deeside",
        "Amber Valley",
        "Arundel and South Downs",
        "Ashfield",
        "Ashford",
        "Ashton-under-Lyne",
        "Aylesbury",
        "Banbury",
        "Banff and Buchan",
        "Barking",
        "Barnsley Central",
        "Barnsley East",
        "Barrow and Furness",
        "Basildon and Billericay",
        "Basingstoke",
        "Bassetlaw",
        "Bath",
        "Batley and Spen",
        "Battersea",
        "Beaconsfield",
        "Bedford",
        "Belfast East",
        "Belfast North",
        "Belfast South",
        "Belfast West",
        "Berwick-upon-Tweed",
        "Berwickshire, Roxburgh and Selkirk",
        "Bethnal Green and Bow",
        "Beverley and Holderness",
        "Bexleyheath and Crayford",
        "Birkenhead",
        "Birmingham, Edgbaston",
        "Birmingham, Erdington",
        "Birmingham, Hall Green",
        "Birmingham, Hodge Hill",
        "Birmingham, Ladywood",
        "Birmingham, Northfield",
        "Birmingham, Perry Barr",
        "Birmingham, Selly Oak",
        "Birmingham, Yardley",
        "Bishop Auckland",
        "Blackburn",
        "Blackpool North and Cleveleys",
        "Blackpool South",
        "Blaenau Gwent",
        "Blaydon",
        "Bletchley and Buckingham",
        "Blyth Valley",
        "Bognor Regis and Littlehampton",
        "Bolsover",
        "Bolton North East",
        "Bolton South East",
        "Bolton West",
        "Bootle",
        "Boston and Skegness",
        "Bournemouth East",
        "Bournemouth West",
        "Bracknell",
        "Bradford East",
        "Bradford South",
        "Bradford West",
        "Braintree",
        "Brecon and Radnorshire",
        "Brent Central",
        "Brent North",
        "Brentford and Isleworth",
        "Bridgend",
        "Bridgwater and West Somerset",
        "Brigg and Goole",
        "Brighton, Kemptown",
        "Brighton, Pavilion",
        "Bristol East",
        "Bristol North West",
        "Bristol South",
        "Bristol West",
        "Broadland",
        "Bromley and Chislehurst",
        "Bromsgrove",
        "Broxbourne",
        "Broxtowe",
        "Buckingham",
        "Burnley",
        "Burton",
        "Bury North",
        "Bury South",
        "Bury St Edmunds",
        "Caerphilly",
        "Caithness, Sutherland and Easter Ross",
        "Calder Valley",
        "Camberwell and Peckham",
        "Cambridge",
        "Cannock Chase",
        "Canterbury",
        "Cardiff Central",
        "Cardiff North",
        "Cardiff South and Penarth",
        "Cardiff West",
        "Carlisle",
        "Carshalton and Wallington",
        "Castle Point",
        "Central Ayrshire",
        "Central Devon",
        "Central Suffolk and North Ipswich",
        "Ceredigion",
        "Charnwood",
        "Chatham and Aylesford",
        "Cheadle",
        "Chelmsford",
        "Chelsea and Fulham",
        "Cheltenham",
        "Chesham and Amersham",
        "Chesterfield",
        "Chichester",
        "Chingford and Woodford Green",
        "Chippenham",
        "Chipping Barnet",
        "Chorley",
        "Christchurch",
        "Cities of London and Westminster",
        "City of Durham",
        "City of York",
        "Clacton",
        "Clapham",
        "Clwyd South",
        "Clwyd West",
        "Coatbridge, Chryston and Bellshill",
        "Colchester",
        "Colne Valley",
        "Congleton",
        "Consett",
        "Conwy",
        "Copeland",
        "Corby",
        "Coventry North East",
        "Coventry North West",
        "Coventry South",
        "Crawley",
        "Crewe and Nantwich",
        "Croydon Central",
        "Croydon North",
        "Croydon South",
        "Cumbernauld, Kilsyth and Kirkintilloch East",
        "Cwmbran",
        "Dagenham and Rainham",
        "Darlington",
        "Dartford",
        "Daventry",
        "Delyn",
        "Derby North",
        "Derby South",
        "Derbyshire Dales",
        "Devizes",
        "Dewsbury",
        "Don Valley",
        "Doncaster Central",
        "Doncaster North",
        "Dorset Mid and North Poole",
        "Dorset South",
        "Dorset West",
        "Dover",
        "Dudley North",
        "Dudley South",
        "Dulwich and West Norwood",
        "Dumfries and Galloway",
        "Dumfriesshire, Clydesdale and Tweeddale",
        "Dundee East",
        "Dundee West",
        "Dunfermline and West Fife",
        "Dunstable",
        "Durham North",
        "Ealing Central and Acton",
        "Ealing North",
        "Ealing Southall",
        "East Antrim",
        "East Ayrshire",
        "East Devon",
        "East Dorset",
        "East Dunbartonshire",
        "East Ham",
        "East Hampshire",
        "East Kilbride, Strathaven and Lesmahagow",
        "East Londonderry",
        "East Lothian",
        "East Renfrewshire",
        "East Riding of Yorkshire",
        "East Surrey",
        "East Worthing and Shoreham",
        "Eastbourne",
        "Eastleigh",
        "Eddisbury",
        "Edinburgh East",
        "Edinburgh North and Leith",
        "Edinburgh South",
        "Edinburgh South West",
        "Edinburgh West",
        "Ellesmere Port and Neston",
        "Elmet and Rothwell",
        "Eltham",
        "Enfield North",
        "Enfield Southgate",
        "Epping Forest",
        "Epsom and Ewell",
        "Erith and Thamesmead",
        "Esher and Walton",
        "Exeter",
        "Falkirk",
        "Faversham and Mid Kent",
        "Feltham and Heston",
        "Fermanagh and South Tyrone",
        "Fife North East",
        "Filton and Bradley Stoke",
        "Finchley and Golders Green",
        "Folkestone and Hythe",
        "Forest of Dean",
        "Foyle",
        "Fraserburgh",
        "Fylde",
        "Gainsborough",
        "Garston and Halewood",
        "Gateshead",
        "Gedling",
        "Gillingham and Rainham",
        "Glasgow Central",
        "Glasgow East",
        "Glasgow North",
        "Glasgow North East",
        "Glasgow North West",
        "Glasgow South",
        "Glasgow South West",
        "Glenrothes",
        "Gloucester",
        "Glyndwr",
        "Goddard",
        "Gordon",
        "Gosport",
        "Gower",
        "Grantham and Stamford",
        "Gravesham",
        "Great Grimsby",
        "Great Yarmouth",
        "Greenwich and Woolwich",
        "Guildford",
        "Hackney North and Stoke Newington",
        "Hackney South and Shoreditch",
        "Halesowen and Rowley Regis",
        "Halifax",
        "Haltemprice and Howden",
        "Hamilton",
        "Hampstead and Kilburn",
        "Harborough",
        "Harlow",
        "Harrogate and Knaresborough",
        "Harrow East",
        "Harrow West",
        "Hartlepool",
        "Harwich and North Essex",
        "Hastings and Rye",
        "Havant",
        "Hayes and Harlington",
        "Hazel Grove",
        "Hemel Hempstead",
        "Hendon",
        "Henley",
        "Hereford and South Herefordshire",
        "Hertford and Stortford",
        "Hertsmere",
        "Hexham",
        "Heywood and Middleton",
        "High Peak",
        "Hitchin and Harpenden",
        "Holborn and St Pancras",
        "Hornchurch and Upminster",
        "Hornsey and Wood Green",
        "Horsham",
        "Houghton and Sunderland South",
        "Hove",
        "Huddersfield",
        "Hull East",
        "Hull North",
        "Hull West and Hessle",
        "Huntingdon",
        "Hyde",
        "Ilford North",
        "Ilford South",
        "Inverclyde",
        "Inverness, Nairn, Badenoch and Strathspey",
        "Ipswich",
        "Isle of Wight",
        "Islington North",
        "Islington South and Finsbury",
        "Keighley",
        "Kensington",
        "Kettering",
        "Kidderminster",
        "Kilmarnock and Loudoun",
        "Kingston and Surbiton",
        "Kingston upon Hull East",
        "Kingston upon Hull North",
        "Kingston upon Hull West and Hessle",
        "Kingswood",
        "Kirkcaldy and Cowdenbeath",
        "Knowsley",
        "Lagan Valley",
        "Lanark and Hamilton East",
        "Lancaster and Fleetwood",
        "Leeds Central",
        "Leeds East",
        "Leeds North East",
        "Leeds North West",
        "Leeds West",
        "Leicester East",
        "Leicester South",
        "Leicester West",
        "Leigh",
        "Leighton Buzzard",
        "Lewes",
        "Lewisham East",
        "Lewisham West and Penge",
        "Leyton and Wanstead",
        "Lichfield",
        "Lincoln",
        "Liverpool, Riverside",
        "Liverpool, Walton",
        "Liverpool, Wavertree",
        "Liverpool, West Derby",
        "Livingston",
        "Llanelli",
        "Londonderry East",
        "Londonderry West",
        "Loughborough",
        "Louth and Horncastle",
        "Ludlow",
        "Luton North",
        "Luton South",
        "Macclesfield",
        "Maidenhead",
        "Maidstone and The Weald",
        "Makerfield",
        "Malton",
        "Manchester Central",
        "Manchester Gorton",
        "Manchester Withington",
        "Mansfield",
        "Margate",
        "Marlow",
        "Marlow South",
        "Marlow West",
        "Marlow North",
        "Marlow East",
        "Marlow Central",
        "Marlow Rural",
        "Marlow Urban",
        "Marlow Town",
        "Marlow Village",
        "Marlow Hamlet",
        "Marlow Parish",
        "Marlow Borough",
        "Marlow District",
        "Marlow County",
        "Marlow City",
        "Marlow Metropolitan",
        "Marlow Suburban",
        "Marlow Industrial",
        "Marlow Commercial",
        "Marlow Residential",
        "Marlow Agricultural",
        "Marlow Educational",
        "Marlow Recreational",
        "Marlow Medical",
        "Marlow Transport",
        "Marlow Energy",
        "Marlow Water",
        "Marlow Waste",
        "Marlow Emergency",
        "Marlow Security",
        "Marlow Technology",
        "Marlow Science",
        "Marlow Arts",
        "Marlow Sports",
        "Marlow Leisure",
        "Marlow Tourism",
        "Marlow Heritage",
        "Marlow Environment",
        "Marlow Community",
        "Marlow Social",
        "Marlow Political",
        "Marlow Economic",
        "Marlow Legal",
        "Marlow Religious",
        "Marlow Cultural",
        "Marlow International",
        "Marlow National",
        "Marlow Regional",
        "Marlow Local",
        "Marlow Rural",
        "Marlow Urban",
        "Marlow Town",
        "Marlow Village",
        "Marlow Hamlet",
        "Marlow Parish",
        "Marlow Borough",
        "Marlow District",
        "Marlow County",
        "Marlow City",
        "Marlow Metropolitan",
        "Marlow Suburban",
        "Marlow Industrial",
        "Marlow Commercial",
        "Marlow Residential",
        "Marlow Agricultural",
        "Marlow Educational",
        "Marlow Recreational",
        "Marlow Medical",
        "Marlow Transport",
        "Marlow Energy",
        "Marlow Water",
        "Marlow Waste",
        "Marlow Emergency",
        "Marlow Security",
        "Marlow Technology",
        "Marlow Science",
        "Marlow Arts",
        "Marlow Sports",
        "Marlow Leisure",
        "Marlow Tourism",
        "Marlow Heritage",
        "Marlow Environment",
        "Marlow Community",
        "Marlow Social",
        "Marlow Political",
        "Marlow Economic",
        "Marlow Legal",
        "Marlow Religious",
        "Marlow Cultural",
        "Marlow International",
        "Marlow National",
        "Marlow Regional",
        "Marlow Local",
        "Marlow Rural",
        "Marlow Urban",
        "Marlow Town",
        "Marlow Village",
        "Marlow Hamlet",
        "Marlow Parish",
        "Marlow Borough",
        "Marlow District",
        "Marlow County",
        "Marlow City",
        "Marlow Metropolitan",
        "Marlow Suburban",
        "Marlow Industrial",
        "Marlow Commercial",
        "Marlow Residential",
        "Marlow Agricultural",
        "Marlow Educational",
        "Marlow Recreational",
        "Marlow Medical",
        "Marlow Transport",
        "Marlow Energy",
        "Marlow Water",
        "Marlow Waste",
        "Marlow Emergency",
        "Marlow Security",
        "Marlow Technology",
        "Marlow Science",
        "Marlow Arts",
        "Marlow Sports",
        "Marlow Leisure",
        "Marlow Tourism",
        "Marlow Heritage",
        "Marlow Environment",
        "Marlow Community",
        "Marlow Social",
        "Marlow Political",
        "Marlow Economic",
        "Marlow Legal",
        "Marlow Religious",
        "Marlow Cultural",
        "Marlow International",
        "Marlow National",
        "Marlow Regional",
        "Marlow Local"
    };

    public static bool IsValidConstituency(string constituency)
    {
        return Constituencies.Contains(constituency);
    }
}
