using System.Collections.Generic;

namespace officialApp.Models;

public static class UKCounties
{
    public static readonly List<string> Counties = new()
    {
        // England
        "Bedfordshire",
        "Berkshire", 
        "Bristol",
        "Buckinghamshire",
        "Cambridgeshire",
        "Cheshire",
        "City of London",
        "Cornwall",
        "Cumbria",
        "Derbyshire",
        "Devon",
        "Dorset",
        "Durham",
        "East Riding of Yorkshire",
        "East Sussex",
        "Essex",
        "Gloucestershire",
        "Greater London",
        "Greater Manchester",
        "Hampshire",
        "Herefordshire",
        "Hertfordshire",
        "Isle of Wight",
        "Kent",
        "Lancashire",
        "Leicestershire",
        "Lincolnshire",
        "Merseyside",
        "Norfolk",
        "North Yorkshire",
        "Northamptonshire",
        "Northumberland",
        "Nottinghamshire",
        "Oxfordshire",
        "Rutland",
        "Shropshire",
        "Somerset",
        "South Yorkshire",
        "Staffordshire",
        "Suffolk",
        "Surrey",
        "Tyne and Wear",
        "Warwickshire",
        "West Midlands",
        "West Sussex",
        "West Yorkshire",
        "Wiltshire",
        "Worcestershire",
        
        // Scotland  
        "Aberdeenshire",
        "Angus",
        "Argyll and Bute",
        "Clackmannanshire",
        "Dumfries and Galloway",
        "Dundee City",
        "East Ayrshire",
        "East Dunbartonshire",
        "East Lothian",
        "East Renfrewshire",
        "Edinburgh",
        "Falkirk",
        "Fife",
        "Glasgow City",
        "Highland",
        "Inverclyde",
        "Midlothian",
        "Moray",
        "North Ayrshire",
        "North Lanarkshire",
        "Orkney Islands",
        "Perth and Kinross",
        "Renfrewshire",
        "Scottish Borders",
        "Shetland Islands",
        "South Ayrshire",
        "South Lanarkshire",
        "Stirling",
        "West Dunbartonshire", 
        "West Lothian",
        "Western Isles",
        
        // Wales
        "Anglesey",
        "Blaenau Gwent",
        "Bridgend",
        "Caerphilly",
        "Cardiff",
        "Carmarthenshire",
        "Ceredigion",
        "Conwy",
        "Denbighshire",
        "Flintshire",
        "Gwynedd",
        "Merthyr Tydfil",
        "Monmouthshire",
        "Neath Port Talbot",
        "Newport",
        "Pembrokeshire",
        "Powys",
        "Rhondda Cynon Taff",
        "Swansea",
        "Torfaen",
        "Vale of Glamorgan",
        "Wrexham",
        
        // Northern Ireland
        "Antrim",
        "Armagh",
        "Down",
        "Fermanagh",
        "Londonderry",
        "Tyrone"
    };
    
    public static bool IsValidCounty(string county)
    {
        return Counties.Contains(county);
    }
}